--DROP

drop table t_restaurant if exists;

--CREATE

create table t_restaurant (
        id integer generated by default as identity (start with 1),
        title varchar(255),
        primary key (id)
    );
    
    